# Generated by Django 5.2.5 on 2025-12-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('university_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('other', 'Other')], default='public', max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
